version: '3.8'
services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=main
            - POSTGRES_USER=usr
            - POSTGRES_PASSWORD=pass
        volumes:
            - main_vol:/var/lib/postgresql/data:rw
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "usr"]

    back:
        image: {{ env.BACKEND_IMAGE }}
        environment:
            - DATABASE_URL=postgresql://usr:pass@postgres:5432/main
            - PORT=3000
        restart: always
        depends_on:
            - postgres
        ports:
            - 3000:3000

    front:
        image: {{ env.FRONTEND_IMAGE }}
        restart: always
        depends_on:
            - back
        ports:
            - 80:80

volumes:
    main_vol: